### ISSUE TITLE
Review requirements for Jupyter notebook

### ISSUE THREAD

**Issue by gcapes** [miamaric12/HAPPY#2]
- [x] In addition to the `setup.py` requirements when you install the package, the jupyter notebook requires pandas (maybe more - that's as far as I got).
- [x] It also gives a warning about numba.
- [x] `%matplotlib qt` doesn't seem to work for me

**Comment by gcapes** [comment]
The numba warning come from the `skan` package so there isn't really anything I can do about that. The rest should now be fixed.

**Comment by jni** [comment]
@gcapes oops! Sorry about that! There *is* something you can do though, submit a PR/issue to the [skan repo!](https://github.com/jni/skan). 😉 It would be much appreciated!

**Comment by gcapes** [comment]
https://github.com/jni/skan/issues/103
