### ISSUE TITLE
HAPPY -> happy/something else?

### ISSUE THREAD

**Issue by jni** [miamaric12/HAPPY#6]
Hello everyone! I hope you're all doing ok.

Just got a notification from the 1.0 tag, that is nice to see! 🎉 Congrats! Together with an Apache license, very nice.

One thing I might suggest is to rename the package (ie what you actually import) from HAPPY to happy. I've never seen packages in allcaps and Python programmers generally dislike capital letters. =P

I also just noticed that `happy` is already an unrelated package on PyPI... =\

Finally, the README needs updating... ;)

**Comment by miamaric12** [comment]
have renamed it on PyPi it is zrHAPPy
